### ISSUE TITLE
Python 3-incompatible

### ISSUE THREAD

**Issue by ericmjl** [maxzheng/memory-tools#1]
Hi Max! I have noticed that in `__init__.py`, [Line 74](https://github.com/maxzheng/memory-tools/blob/master/src/memorytools/__init__.py#L74), you are using the old print statement, which makes it py3k-incompatible. Would you consider a PR to change the print statements?

**Comment by maxzheng** [comment]
Fixed. Also added test for py3. :) Published a new version for it.
Let me know if you see other issues, and also feel free to provide a PR for
new ones.

**Comment by ericmjl** [comment]
Wow, @maxzheng, you're amazing! I will keep an eye on `memory-tools`, and I'm happy to put in PRs for small fixes here and there that I find if you're busy.
